### ISSUE TITLE
error missind dll

### ISSUE THREAD

**Issue by chronoss09** [Storm21CH/PS4-FW-6.72-Payload-Converter#1]
![Capture](https://user-images.githubusercontent.com/17669980/103166995-ab4ff300-4827-11eb-8f76-99de21aa0617.PNG)

**Comment by Storm21CH** [comment]
Hello Chronoss

There must be something wrong with your computer. Never happened to me... Sorry can't help

**Comment by chronoss09** [comment]
ok thanks :) but work well on W10 :+1:
